// ============================================================
// BUILD-DATA — generates ../data.js (the snapshot the offline
// dashboard reads). Combines canonical portfolio defaults with
// freshly fetched feeds and the latest KB digest.
//
// Output is a CLASSIC script (window.__CC__ = {...}) — NOT an ES
// module — because index.html loads it via <script src> under the
// file:// protocol, where ES module imports are blocked by CORS.
//
// Usage:
//   import { buildData } from './build-data.mjs'   (called by daily-brief)
//   node scripts/build-data.mjs                    (standalone refresh)
// ============================================================

import './env.mjs'
import fs from 'node:fs'
import path from 'node:path'
import { ROOT } from './env.mjs'
import {
  COMPANIES, PIPELINE_DEALS_DEFAULT, OKRS_DEFAULT,
  TASKS_DEFAULT, BUILD_STATUS, FEED_SOURCES, STAGES,
} from './data.mjs'
import { fetchAllFeeds } from './feeds.mjs'
import { readLatestDigest } from './digest.mjs'
import { readKBActivity } from './kb.mjs'

/**
 * Assemble the full snapshot object and write ../data.js.
 * Returns the snapshot (so the morning brief can reuse the feeds/digest
 * without re-fetching).
 */
export async function buildData({ fetchFeeds = true } = {}) {
  const generatedAt = new Date().toISOString()

  // Live feeds (best-effort; failures land as empty arrays with an error)
  let feeds = {}
  if (fetchFeeds) {
    try {
      feeds = await fetchAllFeeds(FEED_SOURCES)
    } catch (err) {
      console.error('[build-data] feed fetch failed:', err.message)
      feeds = {}
    }
  }

  // Latest KB digest (may be null)
  const digest = readLatestDigest()

  // Your real business activity from the KB ingest (Gmail/calls/deals),
  // surfaced as a live feed so the dashboard reflects current reality.
  const kb = readKBActivity({ maxDigests: 7, maxItems: 30 })
  const kbSource = {
    id: 'business',
    label: 'Business Activity',
    color: '#22c55e',
    description: 'Live from your KB ingest — deals, intros, signals',
  }
  if (kb.items.length) {
    feeds = {
      business: { ...kbSource, items: kb.items, error: kb.error, fetchedAt: generatedAt },
      ...feeds,
    }
  }

  // Put Business Activity first in the source list so it leads the Feeds tab.
  const feedSources = [
    ...(kb.items.length ? [kbSource] : []),
    ...FEED_SOURCES.map(({ id, label, color, description }) => ({ id, label, color, description })),
  ]

  const snapshot = {
    generatedAt,
    companies: COMPANIES,
    deals: PIPELINE_DEALS_DEFAULT,
    okrs: OKRS_DEFAULT,
    tasks: TASKS_DEFAULT,
    builds: BUILD_STATUS,
    stages: STAGES,
    feedSources,
    feeds,
    digest,
  }

  const banner =
    '// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.\n' +
    `// Generated: ${generatedAt}\n` +
    '// Loaded by index.html as a classic script (sets window.__CC__).\n'

  const body = `${banner}window.__CC__ = ${JSON.stringify(snapshot, null, 2)};\n`

  const outPath = path.join(ROOT, 'data.js')
  fs.writeFileSync(outPath, body, 'utf8')

  return { snapshot, outPath }
}

// ---- Standalone entrypoint -----------------------------------
// `node scripts/build-data.mjs`  → refresh dashboard data only (no email).
if (process.argv[1] && process.argv[1].endsWith('build-data.mjs')) {
  buildData({ fetchFeeds: true })
    .then(({ outPath, snapshot }) => {
      const feedCounts = Object.values(snapshot.feeds || {})
        .map((f) => `${f.label}:${f.items.length}`)
        .join('  ')
      console.log(`✓ Wrote ${outPath}`)
      console.log(`  Feeds → ${feedCounts || '(none)'}`)
      console.log(`  Digest → ${snapshot.digest ? snapshot.digest.filename : '(none found)'}`)
    })
    .catch((err) => {
      console.error('✗ build-data failed:', err)
      process.exit(1)
    })
}
